export const siteConfig = {
  name: 'قدیر لوله آنلاین',
  nameEn: 'Qadir Lule Online',
  description: 'تامین کننده انواع لوله، اتصالات و تجهیزات صنعتی در مشهد. با بیش از ۲۰ سال تجربه در صنعت لوله و اتصالات.',
  url: 'https://luleonline-mashhad.ir',
  phone: '09121184970',
  mobile: '09123837505',
  email: 'atlastejaratazhand@gmail.com',
  address:' ',
  workingHours: 'شنبه تا پنجشنبه: ۸ صبح تا ۶ عصر',
  socials: {
    // instagram: 'https://instagram.com/luleonlinemashhad',
    // telegram: 'https://t.me/luleonlinemashhad',
    whatsapp: 'https://wa.me/989123837505',
    // linkedin: 'https://linkedin.com/company/luleonlinemashhad',
  },
  keywords: [
    'لوله مشهد',
    'لوله فروشی مشهد',
    'اتصالات لوله مشهد',
    'لوله پلیکا مشهد',
    'لوله پلی اتیلن مشهد',
    'لوله چدن داکتیل مشهد',
    'منهول مشهد',
    'شیرآلات صنعتی مشهد',
    'لوله فولادی مشهد',
    'لوله مانیسمان مشهد',
    'فلنج مشهد',
    'تامین لوله و اتصالات خراسان',
    'قدیر لوله آنلاین',
    'خرید لوله صنعتی',
    'لوله آب و فاضلاب مشهد',
  ],
};
